language: node_js
node_js:
- 7.10.0
after_success:
- npm run build
- ls
before_deploy:
- cd dist
- ls
deploy:
  provider: npm
  email: leandro.diniz@outlook.com.br
  skip_cleanup: true
  api_key:
    secure: $NPM_TOKEN
  on:
    branch: master
