language: node_js
node_js:
  - 8
  - 7
after_success:
  - npm run build
  before_deploy:
  - cd dist
deploy:
  provider: npm
  email: alison.vilela@live.nl
  skip_cleanup: true
  api_key:
    secure: $NPM_TOKEN
  on:
    branch: master