language: node_js
node_js:
  - 7.10.0
script:
  - npm install
  - npm run build
before_deploy:
  - cd dist
deploy:
  provider: npm
  email: alison.vilela@live.nl
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master